"""Generate and statically review a constrained pytest adapter."""

from __future__ import annotations

import ast
from pathlib import Path

from api_agent.models import ScriptReviewReport, TestCaseDocument


TEST_TEMPLATE = '''"""Generated by api_agent V1. Do not edit; regenerate from test-cases.json."""

import os
from pathlib import Path

import pytest

from api_agent.artifacts import read_model
from api_agent.executor import ScenarioExecutor
from api_agent.models import NormalizedRequirement, TestCaseDocument


CASES_PATH = Path(os.environ["API_AGENT_CASES_PATH"])
REQUIREMENT_PATH = Path(os.environ["API_AGENT_REQUIREMENT_PATH"])
CASES = read_model(CASES_PATH, TestCaseDocument).cases


@pytest.fixture(scope="session")
def scenario_executor():
    executor = ScenarioExecutor(
        base_url=os.environ["API_AGENT_BASE_URL"],
        database_url=os.environ["API_AGENT_DATABASE_URL"],
        evidence_dir=Path(os.environ["API_AGENT_EVIDENCE_DIR"]),
        run_id=os.environ["API_AGENT_RUN_ID"],
        requirement=read_model(REQUIREMENT_PATH, NormalizedRequirement),
    )
    yield executor
    executor.close()


@pytest.mark.parametrize("case", CASES, ids=[case.case_id for case in CASES])
def test_generated_api_case(case, scenario_executor):
    evidence = scenario_executor.execute(case)
    failed = [item for item in evidence.assertions if item.status != "passed"]
    assert evidence.status == "passed", [item.model_dump() for item in failed]
'''


def generate_pytest(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(TEST_TEMPLATE, encoding="utf-8")


def review_generated_script(path: Path, cases: TestCaseDocument) -> ScriptReviewReport:
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(path))
    issues: list[str] = []
    forbidden_imports = {"subprocess", "socket"}
    forbidden_calls = {"eval", "exec", "compile", "os.system", "os.popen"}
    imports: set[str] = set()
    calls: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imports.update(alias.name.split(".")[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imports.add(node.module.split(".")[0])
        elif isinstance(node, ast.Call):
            name = _call_name(node.func)
            if name:
                calls.add(name)
    if found := sorted(imports & forbidden_imports):
        issues.append(f"Forbidden imports: {', '.join(found)}")
    if found := sorted(calls & forbidden_calls):
        issues.append(f"Forbidden calls: {', '.join(found)}")
    if "ScenarioExecutor" not in source:
        issues.append("Generated script does not use the controlled ScenarioExecutor")
    if "pytest.mark.parametrize" not in source:
        issues.append("Generated script does not map test-cases.json to pytest")

    mapped = [case.case_id for case in cases.cases] if not issues else []
    missing = [case.case_id for case in cases.cases if case.case_id not in mapped]
    return ScriptReviewReport(
        decision="approved" if not issues and not missing else "needs_revision",
        script_path=str(path),
        mapped_case_ids=mapped,
        missing_case_ids=missing,
        issues=issues,
    )


def _call_name(node: ast.AST) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        parent = _call_name(node.value)
        return f"{parent}.{node.attr}" if parent else node.attr
    return None

